Add location mapping july52022
XLSForm/xlsform.github.io pull request #227
Opened 2022-07-05 15:42 UTC by msschroeder

I have added updates to the XLSForm Content Documentation highlight the key changes to the syntax. There will be one more pull request as I could not edit the update file included as a part of the main and I forgot to include the update to the appearance section.

2022-07-06 21:12 UTC, lognaturel requested changes
Couple suggestions to consider!

2022-07-06 21:12 UTC, lognaturel commented on _sections/home-english.md
> +Note that, this question type is generally the preferred way of building select questions from external data as it is the most versatile and works across applications. However, if your external data
I think the original sentence better captured the intent! What it's saying is that if this way of attaching external data is slow in a particular context, there are other options.

2022-07-06 21:12 UTC, lognaturel commented on _sections/home-english.md
> +| map, quick map       | select_one, select_one_from_file | Allows a user to select a choice from many locations on a map |
locations -> features

2022-07-12 13:33 UTC, msschroeder commented on _data/choices.csv
> +geometry,Displays choices on map as locations,✔,✔,,
I have updated this.

2023-01-25 00:08 UTC, lognaturel approved these changes

2023-01-25 00:08 UTC, merged